#!/bin/bash
#
# Test the PHP S2I image in OpenShift (remote cluster)
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
# VERSION specifies the major version of the PHP runtime in format of X.Y
# OS specifies RHEL version (e.g. OS=rhel7)
#

THISDIR=$(dirname ${BASH_SOURCE[0]})

source "${THISDIR}/test-lib-php.sh"
source "${THISDIR}/test-lib-openshift.sh"
source "${THISDIR}/test-lib-remote-openshift.sh"

TEST_LIST="\
test_php_integration
test_php_imagestream
"

trap ct_os_cleanup EXIT SIGINT

ct_os_check_compulsory_vars || exit $OC_ERR

ct_os_set_ocp4 || exit $OC_ERR

oc version

ct_os_check_login || exit $OC_ERR

ct_os_tag_image_for_cvp "php"

set -u

# For testing on OpenShift 4 we use OpenShift internal registry
export CT_OCP4_TEST=true

TEST_SUMMARY=''
TEST_SET=${TESTS:-$TEST_LIST} ct_run_tests_from_testset "openshift-remote-cluster"
# vim: set tabstop=2:shiftwidth=2:expandtab:

