#!/bin/bash

set -x

shopt -s dotglob ## para mover los archivos ocultos
set -eo pipefail

## Lo instala en /opt/app-root/src
if [ -z "$WP_INSTALL_VERSION" ]; then
    wp core download --locale=es_ES --version=latest --path="/."
else
    wp core download --locale=es_ES --version="$WP_INSTALL_VERSION" --path="./"
fi





fix-permissions ./
fix-permissions /opt/app-root
