#!/bin/bash

set -x

set -eo pipefail

shopt -s dotglob ## para mover los archivos ocultos




if [ -f "/opt/app-root/silo/wp-config.php" ];then
    # rm -f "/opt/app-root/src/wp-config.php"
    # rm -f "/opt/app-root/src/wp-config-sample.php"
    gulp tmoverwpconfigpriv
    # mv /opt/app-root/silo/wp-config.php /silo/wordpress
    # ln -sf "/opt/app-root/silo/wordpress/wp-config.php" "/opt/app-root/src"
fi

if [ -d "/opt/app-root/silo/wordpress/wp-content" ];then
    # rm -rf "/opt/app-root/src/wp-content"
    gulp tmoverwpcontentpriv
    # mv /opt/app-root/silo/wp-content /silo/wordpress
    # ln -sf "/opt/app-root/silo/wordpress/wp-content" "/opt/app-root/src"
fi


if [ -f "/opt/app-root/silo/wordpress/.htaccess" ];then
    # rm -f "/opt/app-root/src/.htcaccess"
    gulp tmoverwphtcaccesspriv
    # mv /opt/app-root/silo/.htcaccess /silo/wordpress
    # ln -sf "/opt/app-root/silo/wordpress/.htaccess" "/opt/app-root/src"
fi

gulp default &


if [ -z "${DB_USER}" ] ||  [ -z "${DB_PASSWORD}" ] ||  [ -z "${DB_NAME}" ] ||  [ -z "${DB_HOST}" ];then
    echo "Procedemos desde el propio instalador php de wordpress (web) mediante el browser."
else
    wp config create --dbname="${DB_NAME}" --dbuser="${DB_USER}" --dbpass="${DB_PASSWORD}" --dbhost="${DB_HOST}" --skip-check
    wp db create
fi



if [ -f "/opt/app-root/src/wp-content" ];then
    # rm -f "/opt/app-root/src/.htcaccess"
    gulp tmoverwpcontent
    # mv /opt/app-root/silo/.htcaccess /silo/wordpress
    # ln -sf "/opt/app-root/silo/wordpress/.htaccess" "/opt/app-root/src"
fi

if [ -f "/opt/app-root/src/.htaccess" ];then
    # rm -f "/opt/app-root/src/.htcaccess"
    gulp tmoverwphtcaccess
    # mv /opt/app-root/silo/.htcaccess /silo/wordpress
    # ln -sf "/opt/app-root/silo/wordpress/.htaccess" "/opt/app-root/src"
fi






# Execute the original run script, replacing this script as current process.

exec /usr/libexec/s2i/run
