#!/bin/bash

set -x

set -eo pipefail

shopt -s dotglob ## para mover los archivos ocultos

if [ -f "/opt/app-root/silo/wordpress/wp-config.php" ];then
    rm -f "/opt/app-root/src/wp-config.php"
    ln -sf "/opt/app-root/silo/wordpress/wp-config.php" "/opt/app-root/src"
fi

if [ -d "/opt/app-root/silo/wordpress/wp-content" ];then
    rm -rf "/opt/app-root/src/wp-content"
    ln -sf "/opt/app-root/silo/wordpress/wp-content" "/opt/app-root/src"
fi


if [ -f "/opt/app-root/silo/wordpress/.htaccess" ];then
    rm -f "/opt/app-root/src/.htcaccess"
    ln -sf "/opt/app-root/silo/wordpress/.htaccess" "/opt/app-root/src"
fi


# Execute the original run script, replacing this script as current process.

exec /usr/libexec/s2i/run
