#!/bin/bash

set -e

# In order to drop the root user, we have to make some directories world
# writeable as OpenShift default security model is to run the container under
# random UID.

source ${PHP_CONTAINER_SCRIPTS_PATH}/common.sh

# compatibility symlinks so we hide SCL paths
if [ -v SCL_ENABLED ] ; then
  # /opt/rh/httpd24/root/etc/httpd will be symlink to /etc/httpd
  mv /opt/rh/httpd24/root/etc/httpd /etc/httpd
  ln -s /etc/httpd /opt/rh/httpd24/root/etc/httpd

  # /opt/rh/httpd24/root/var/run/httpd will be symlink to /var/run/httpd
  mv /opt/rh/httpd24/root/var/run/httpd /var/run/httpd
  ln -s /var/run/httpd /opt/rh/httpd24/root/var/run/httpd

  # /opt/rh/httpd24/root/var/www will be symlink to /var/www
  rm -rf /var/www
  mv ${HTTPD_DATA_ORIG_PATH} /var/www
  ln -s /var/www ${HTTPD_DATA_ORIG_PATH}
else
  rm -f /opt/app-root/etc/scl_enable
fi

if head "/etc/redhat-release" | grep -q "^Red Hat Enterprise Linux release 8"; then
    /usr/libexec/httpd-ssl-gencerts
fi

mkdir -p ${HTTPD_CONFIGURATION_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_PATH}
chmod -R a+rwx ${HTTPD_MAIN_CONF_D_PATH}
chmod -R ug+r   /etc/pki/tls/certs/localhost.crt
chmod -R ug+r   /etc/pki/tls/private/localhost.key
chown -R 1001:0 /etc/pki/tls/certs/localhost.crt
chown -R 1001:0 /etc/pki/tls/private/localhost.key
mkdir -p ${APP_ROOT}/etc
chmod -R a+rwx ${APP_ROOT}/etc
chmod -R a+rwx ${HTTPD_VAR_RUN}
chown -R 1001:0 ${APP_ROOT}
mkdir /tmp/sessions
chmod -R a+rwx /tmp/sessions
chown -R 1001:0 /tmp/sessions
chown -R 1001:0 ${HTTPD_DATA_PATH}
chmod -R a+rwx ${PHP_SYSCONF_PATH}


######
chmod -R a+rwx /etc/opt/rh/rh-php${PHP_VER_SHORT}/php.d
chmod a+rw /etc/opt/rh/rh-php${PHP_VER_SHORT}/php.ini
chmod a+rwX /var/opt/rh/rh-php${PHP_VER_SHORT}/run/php-fpm
chmod -R a+rwX /var/opt/rh/rh-php72/lib/php
# chmod -R a+rwX /opt/rh/rh-nodejs10/root/usr/lib/node_modules

######

######

######## Creo el directorio /silo
# Aqui se guardará todo lo concerniente al sitio worpress (wp-content, wp-config.php, htcaccess, los certificados del sitio)

mkdir -p /silo/wordpress

chmod -R a+rwX /silo && \
    chmod -R a+rwX /silo && \
    chmod -R ug+r  /silo && \
    chmod -R ug+r  /silo && \
    chown -R 1001:0 /silo && \
    chown -R 1001:0 /silo 
########


########

# Creo el directorio /silo/nodejs/.npm-global/bin 
# Aqui es dónde se guardarán los paquetes globales en .npm-global
# Necesitamos añadir el path, en el Dockerfile
# PATH=$PATH:/opt/rh/rh-php72/root/usr/bin:/opt/rh/rh-mysql80/root/usr/bin/:/silo/nodejs/.npm-global/bin


# mkdir -p /opt/app-root/nodejs/.npm-global
# chmod -R a+rwX /opt/app-root/nodejs && \
# chmod -R a+rwX /opt/app-root/nodejs && \
# chmod -R ug+r  /opt/app-root/nodejs && \
# chmod -R ug+r /opt/app-root/nodejs && \
# chown -R 1001:0 /opt/app-root/nodejs && \
# chown -R 1001:0  /opt/app-root/nodejs 
########








mkdir -p ${PHP_CONTAINER_SCRIPTS_PATH}/pre-init

config_general

