#!/bin/bash

set -x

set -eo pipefail

shopt -s dotglob ## para mover los archivos ocultos


if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ] || [ -z "$DB_NAME" ] || [ -z "$DB_HOST" ]; then

else
fi



# secret() {
#     python -c 'import random; import string; print("".join([random.SystemRandom().choice(string.ascii_letters+string.digits) for i in range(50)]))'
# }

# config_wp_config() {

#      sed -i '/DB_COLLATE/a\
# define('"'"'FORCE_SSL_ADMIN'"'"', true);\
# if (strpos(\$_SERVER['"'"'HTTP_X_FORWARDED_PROTO'"'"'], '"'"'https'"'"') !== false) \$_SERVER['"'"'HTTPS'"'"']='"'"'on'"'"';' "/opt/app-root/silo/wordpress/wp-config.php"


#     sed -i '/table_prefix/a\
# define( '"'"'WP_CONTENT_DIR'"'"', '"'"'/opt/app-root/silo/wordpress'"'"');\
# define( '"'"'WP_PLUGIN_DIR'"'"', WP_CONTENT_DIR . '"'"'/plugins'"'"' );\
# define('"'"'WP_HOME'"'"', '"'"'http://'"'"' . $_SERVER['"'"'HTTP_HOST'"'"'] . '"'"'/'"'"');\
# define('"'"'WP_SITEURL'"'"', '"'"'http://'"'"' . $_SERVER['"'"'HTTP_HOST'"'"'] . '"'"'/'"'"');' "/opt/app-root/silo/wordpress/wp-config.php"

#     sed -i '/.* all, stop editing! Happy publishing/a\
# define('"'"'FS_METHOD'"'"', '"'"'direct'"'"');\
# if ( defined( '"'"'WP_CLI'"'"' ) ) {\n\t$_SERVER['"'"'HTTP_HOST'"'"'] = '"'"'localhost'"'"';\n};' "/opt/app-root/silo/wordpress/wp-config.php"

 


# sed -i "s/'DB_NAME', *'database_name_here'/'DB_NAME', '$DB_NAME'/
# s/'DB_USER', *'username_here'/'DB_USER', '$DB_USER'/
# s/'DB_PASSWORD', *'password_here'/'DB_PASSWORD', '$DB_PASSWORD'/ 
# s/'DB_HOST', *'localhost'/'DB_HOST', '$DB_HOST:$DB_PORT_NUMBER'/
# s/\$table_prefix *= *'wp_';/\$table_prefix = '$DB_TABLE_PREFIX';/
# s/'AUTH_KEY', *'put your unique phrase here'/'AUTH_KEY', '`secret`'/
# s/'SECURE_AUTH_KEY', *'put your unique phrase here'/'SECURE_AUTH_KEY', '`secret`'/
# s/'LOGGED_IN_KEY', *'put your unique phrase here'/'LOGGED_IN_KEY', '`secret`'/
# s/'NONCE_KEY', *'put your unique phrase here'/'NONCE_KEY', '`secret`'/
# s/'AUTH_SALT', *'put your unique phrase here'/'AUTH_SALT', '`secret`'/
# s/'SECURE_AUTH_SALT', *'put your unique phrase here'/'SECURE_AUTH_SALT', '`secret`'/
# s/'LOGGED_IN_SALT', *'put your unique phrase here'/'LOGGED_IN_SALT', '`secret`'/
# s/'NONCE_SALT', *'put your unique phrase here'/'NONCE_SALT', '`secret`'/" /opt/app-root/silo/wordpress/wp-config.php


# cat <<EOF >> /opt/app-root/silo/wordpress/wp-config.php

# if ( ! defined( 'WP_CLI' ) ) {
#     // remove x-pingback HTTP header
#     add_filter('wp_headers', function(\$headers) {
#         unset(\$headers['X-Pingback']);
#         return \$headers;
#     });
#     // disable pingbacks
#     add_filter( 'xmlrpc_methods', function( \$methods ) {
#             unset( \$methods['pingback.ping'] );
#             return \$methods;
#     });
#     add_filter( 'auto_update_translation', '__return_false' );
# }

# EOF
    
# }

# create_htcaccess() {
# 	cat <<EOF > /opt/app-root/silo/wordpress/.htaccess
# # BEGIN WordPress


# RewriteEngine On
# RewriteBase /
# RewriteRule ^index\.php$ - [L]
# RewriteCond %{REQUEST_FILENAME} !-f
# RewriteCond %{REQUEST_FILENAME} !-d
# RewriteRule . /index.php [L]

# # END WordPress
# EOF

# }

# # if [ -v PRIVATE_USER ]; then
# #     echo "pasa por 2a compilacion $(date)\n $PRIVATE_USER" >> /opt/app-root/segundaCompilacion
  
# # else
# #     echo "pasa por 1a compilacion $(date)\n $PRIVATE_USER" >> /opt/app-root/primeraCompilacion
# # fi




# if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ] || [ -z "$DB_NAME" ]; then
#     if [ -f "/opt/app-root/silo/wordpress/wp-config.php" ]; then
#         rm -f /opt/app-root/silo/wordpress/wp-config-sample.php
#         ln -sf /opt/app-root/silo/wordpress/wp-config.php /opt/app-root/src
#     else
#         rm -f /opt/app-root/silo/wordpress/wp-config-sample.php
#         mv /opt/app-root/src/wp-config-sample.php /opt/app-root/silo/wordpress
#         ln -sf /opt/app-root/silo/wordpress/wp-config-sample.php /opt/app-root/src
#     fi
# else
#     if [ -f "/opt/app-root/silo/wordpress/wp-config.php" ]; then
#         rm -f /opt/app-root/silo/wordpress/wp-config-sample.php
#         rm -f /opt/app-root/src/wp-config-sample.php
#         ln -sf /opt/app-root/silo/wordpress/wp-config.php /opt/app-root/src
#     else
#         rm -f /opt/app-root/silo/wordpress/wp-config-sample.php
#         mv /opt/app-root/src/wp-config-sample.php /opt/app-root/silo/wordpress/wp-config.php
#         ln -sf /opt/app-root/silo/wordpress/wp-config.php /opt/app-root/src
#     fi

#     config_wp_config
# fi

# if [ ! -d "/opt/app-root/silo/wordpress/wp-content" ]; then
#     mv /opt/app-root/src/wp-content /opt/app-root/silo/wordpress 
#     ln -sf /opt/app-root/silo/wordpress/wp-content /opt/app-root/src
# else
#     rm -fr /opt/app-root/src/wp-content
#     ln -sf /opt/app-root/silo/wordpress/wp-content /opt/app-root/src
# fi


# # ln -sf /opt/app-root/silo/wordpress/wp-config.php /opt/app-root/src
# # ln -sf /opt/app-root/silo/wordpress/wp-content /opt/app-root/src

# if [ ! -f "/opt/app-root/silo/wordpress/.htcaccess" ]; then
# 		create_htcaccess
#     ln -sf /opt/app-root/silo/wordpress/.htaccess /opt/app-root/src
  
# fi







# Execute the original run script, replacing this script as current process.

exec /usr/libexec/s2i/run
